open_graph:
  enable: true
  twitter_id: # for open_graph meta
article:
  type: story # tech/story
  auto_excerpt: 200
  related_posts:
    enable: false
    max_count: 5
  title: 您可能感兴趣的文章
  license: '本文采用 [署名-非商业性使用-相同方式共享 4.0 国际](https://creativecommons.org/licenses/by-nc-sa/4.0/) 许可协议，转载请注明出处。'

logo:
  subtitle: '开发糕手 | hello' # '文字1 | 文字2' (鼠标放上去会切换到文字2)
  avatar: '[{config.avatar}](/about/)' # you can set avatar link in _config.yml or '[https://xxx.png](/about/)'

appearance:
  preset: minimal
  color_scheme: auto
  colors:
    primary: '#39a7b5'
    accent: '#ee7858'
    link: '#287cc1'


